Part 2 - NutriBullet/NutriBullet/NutriBullet/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('foods/', include('foods.urls')),
    path('users/', include('users.urls'))

]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Part 2 - NutriBullet/NutriBullet/foods/urls.py
from django.urls import path
from . import views


app_name='foods'

urlpatterns = [
    path('<slug:food_type>', views.foods_list, name="list"),
    path('<slug:food_type>/<slug:slug>', views.food_page, name="page")

]

Part 2 - NutriBullet/NutriBullet/users/urls.py
from django.urls import path
from . import views


app_name='users'

urlpatterns = [
    path('register/', views.register_view, name="register"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),

]

Part 2 - NutriBullet/NutriBullet/foods/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

# Create your models here.
class Food(models.Model):
    class FoodType(models.TextChoices):
        MEAT = 'MEAT', _("Meat")
        FRUIT = 'FRUIT', _("Fruit")
        VEGETABLE = 'VEGETABLE', _("Vegetable")
        GRAINS = 'GRAINS', _("Grains")
        DAIRY = 'DAIRY', _("Dairy")
        NUTS = 'NUTS', _("Nuts")
        SUGAR = 'SUGAR', _("Sugar")
        BEVERAGES = 'BEVERAGES', _("Beverages")
    name = models.CharField(max_length=20)
    food_type = models.SlugField(choices=FoodType.choices, default=FoodType.MEAT)
    kcal = models.FloatField()
    fat = models.FloatField()
    saturated_fat = models.FloatField()
    carbohydrates = models.FloatField()
    sugars = models.FloatField()
    protein = models.FloatField() 
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)

    def __str__(self):
        return self.name

Part 2 - NutriBullet/NutriBullet/users/models.py
from django.db import models

# Create your models here.

Part 2 - NutriBullet/NutriBullet/foods/forms.py
from django import forms
from . import models

class CreatePost(forms.ModelForm):
    class Meta:
        model = models.Food
        fields = ['name', 'slug', 'banner']

Part 2 - NutriBullet/NutriBullet/NutriBullet/views.py
from django.shortcuts import render



def homepage(request):
    return render(request, 'home.html')

Part 2 - NutriBullet/NutriBullet/foods/views.py
from django.shortcuts import render
from .models import Food
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
@login_required(login_url="/users/login/")
def foods_list(request, food_type):
    foods = Food.objects.all().filter(food_type = food_type)
    return render(request, 'foods/foods_list.html', {'foods':foods})

@login_required(login_url="/users/login/")
def food_page(request, food_type, slug):
    food = Food.objects.get(slug=slug)
    return render(request, 'foods/food_page.html', {'food':food})

Part 2 - NutriBullet/NutriBullet/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

# Create your views here.
def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save()) 
            return redirect("/")
    else:    
        form = UserCreationForm()
    return render(request, "users/register.html", {"form": form})



def login_view(request): 
    if request.method == "POST": 
        form = AuthenticationForm(data=request.POST)
        if form.is_valid(): 
            login(request, form.get_user())
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("/")
    else: 
        form = AuthenticationForm()
    return render(request, "users/login.html", { "form": form })


def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("/")

Part 2 - NutriBullet/NutriBullet/foods/templates/foods/food_page.html
{% extends 'layout.html' %}

{% block title %}
    {{food.name}}
{% endblock %}

{% block content %}

    <div class="container text-center">
        <h1>Nutrients in 100g of {{food.name}}:</h1>
        <div class="container text-center d-flex justify-content-center mt-4">
            <div class="card bg-success w-15 col-4" style="width: 18rem;">
                <img style="width:100%; height:256px;" class="card-img-top" src="{{food.banner.url}}" alt="{{food.name}}"/>
                <ul class="list-group list-group-flush">
                  <li class="list-group-item bg-success"><i><b> Energy</i>: {{food.kcal}} kcal</b></li>
                  <li class="list-group-item bg-success"><i><b>Fat</i>: {{food.fat}}g - of which saturated: {{food.saturated_fat}}g</b></li</li>
                  <li class="list-group-item bg-success"><i><b>Carbohydrates</i>: {{food.carbohydrates}}g - of which sugars: {{food.sugars}}</b></li</li>
                  <li class="list-group-item bg-success"><i><b>Protein</i>: {{food.protein}}g</b></li</li>
                </ul>
              </div>
        </div>
    </div>
    
{% endblock  %}

Part 2 - NutriBullet/NutriBullet/foods/templates/foods/foods_list.html
{% extends 'layout.html' %}

{% block title %}
    Foods
{% endblock %}

{% block content %}
    <div class="container">
        <h1 class="mb-4">Foods: {{food.food_type}}</h1>

        <table id="tblData" class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>Image</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for food in foods %}
                <tr>
                    <td><img style="width:30px;height:32px;" src="{{food.banner.url}}"></td>
                    <td><b>{{food.name}}</b></td>
                    <td>{{food.food_type}}</td>
                    <td><a class="btn btn-outline-dark" href="{% url 'foods:page' food_type=food.food_type slug=food.slug %}">
                        Details
                    </a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock  %}

Part 2 - NutriBullet/NutriBullet/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Home Page</h1>

    {% if user.is_authenticated %}
        <h4 class="mt-3">Hello {{user}}, </h4>
        <h4 class="mt-3 ms-4">Please select a food category:</h4>

        <div class="row text-center mt-3">
            <div class="col-3 m-4">
                <a class="fs-4 link-secondary" href="/foods/MEAT" aria-label="MEAT" title="MEAT">
                    🥩 MEAT
                </a>
            </div>
            <div class="col-3 m-4">
                <a class="fs-4 link-secondary" href="/foods/DAIRY" aria-label="DAIRY" title="DAIRY">
                    🥛 DAIRY
                </a>
            </div>
            <div class="col-3 m-4">
                <a class="fs-4 link-secondary" href="/foods/FRUIT" aria-label="FRUITS" title="FRUITS">
                    🍉 FRUITS
                </a>
            </div>
            <div class="col-3 m-4">
                <a class="fs-4 link-secondary" href="/foods/VEGETABLE" aria-label="VEGETABLES" title="VEGETABLES">
                   🥕 VEGETABLES
                </a>
            </div>
            <div class="col-3 m-4">
                <a class="fs-4 link-secondary" href="/foods/GRAINS" aria-label="GRAINS" title="GRAINS">
                    🌾 GRAINS 
                </a>
            </div>
            <div class="col-3 m-4">
                <a class="fs-4 link-secondary" href="/foods/NUTS" aria-label="NUTS" title="NUTS">
                    🥜 NUTS
                </a>
            </div>
            <div class="col-3 m-4">
                <a class="fs-4 link-secondary" href="/foods/SUGAR" aria-label="SUGAR" title="SUGAR">
                    🍬 SWEETS
                </a>
            </div>
            <div class="col-3 m-4">
                <a class="fs-4 link-secondary" href="/foods/BEVERAGES" aria-label="BEVERAGES" title="BEVERAGES">
                    🍷 BEVERAGES
                </a>
            </div>
        </div>
        <div class="row">

        </div>

    {% else %}
        <h4>Please <a href="/users/login">login</a> to use our services</h4>
    {% endif %}

    
    
{% endblock  %}

Part 2 - NutriBullet/NutriBullet/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            NutriBullet
        {% endblock %}
    </title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />

</head>
<body style="background-color: gold">
    <header style="background-color: green">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark bg-opacity-50 border-bottom box-shadow mb-3">
                <a class="navbar-brand ms-3" href="/"><b>NutriBullet</b></a> 
                <a class="nav-link link-light" href="/">Home</a>
                <a class="nav-link link-light" href="/admin" title="Admin Panel">Admin Panel</a>
                {% if user.is_authenticated %}
                    <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %}
                    <button class="btn btn-outline-light">Logout</button>
                    </form>
                {% else %}
                    <a class="nav-link link-light" href="{% url 'users:login' %}" title="User Login">Login</a> 
                    <a class="nav-link link-light" href="{% url 'users:register' %}" title="User Registration">Register</a> 
                {% endif %}
        </nav>
    </header>
    <main>
        <div class="container mt-5">
            {% block content %}

            {% endblock %}
        </div> 
    </main>
    <footer class="border-top footer text-muted mt-5">
        <div class="container text-center">
            &copy; 2021 - NutriBullet
        </div>
    </footer>
</body>
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src = "https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>

<script>
$(document).ready( function () {
    $('#tblData').DataTable();
} );


</script>
</html>

Part 2 - NutriBullet/NutriBullet/users/templates/users/login.html
{% extends 'layout.html' %}

{% block title %}
    Login
{% endblock %}

{% block content %}
    <h1 class="mb-4">User Login</h1>
    <form action="/users/login/" method="post">
        {% csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input class="form-control" type="hidden" name="next" value="{{request.GET.next}}"/>
        {% endif %}
        <button class="btn btn-light ms-3" type="submit">Submit</button>
    </form>
{% endblock  %}

Part 2 - NutriBullet/NutriBullet/users/templates/users/register.html
{% extends 'layout.html' %}

{% block title %}
    Register a new user
{% endblock %}

{% block content %}
    <h1 class="mb-4">Register a new User</h1>
    <form action="/users/register/" method="post">
        {% csrf_token %}
        {{form}}
        <button class="btn btn-light ms-3" type="submit">Submit</button>
    </form>
{% endblock  %}